services: docker
env:
- distro: ubuntu1604
- distro: ubuntu1404
- distro: debian8
script:
- export container_id=$(date +%s)
- export cleanup=false
- wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
- chmod +x ${PWD}/tests/test.sh
- "${PWD}/tests/test.sh"
- 'sudo docker exec ${container_id} sudo mysql -u root -proot -h 127.0.0.1 -e ''show
  databases;'' | grep -q ''mysql_prepare_db''

'
- 'sudo docker exec ${container_id} sudo mysql -u root -proot -h 127.0.0.1 -e ''SELECT
  count(*) FROM `mysql_prepare_db`.`test_table`;'' | grep -q ''8''

'
- 'sudo docker exec ${container_id} sudo mysql -u root -proot -h 127.0.0.1 -e ''SELECT
  `color` FROM `mysql_prepare_db`.`test_table` WHERE `color_name` = "color_3"'' |
  grep -q ''not_a_color''

'
- 'sudo docker exec ${container_id} sudo mysql -u root -proot -h 127.0.0.1 -e ''SELECT
  `color` FROM `mysql_prepare_db`.`test_table` WHERE `id` = 8;'' | grep -q ''bordeaux''

'
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      secure: ElgO8hMtyXcvi1aIgDL9r7Poi2PL98fyhCiWA8u1ypgMmLsmFclFPxwHEgCCJDEeHInEExHqDG7+mZy1s+Haoj2bxfZBFP6sDGkkPrQ7CIRx7WY8VE4vnLxkDBqwUChPXHc60Tz5CHCf/jHZIT3edXp5rOGctKP3tzsp/DoVAsz7dwUso4df4/HgzFAFUb8gDTYTYlC3pk3SV7WiYZB72oBBpVZmhrrpD20DndSCF/FhVQjqUjXwrrz8XvNGmc/edRnE713WyZMOVl5PJspWkzBvbuWXmo6m23Mj9k+qZ41YByfyjlFuPAABYuN46wMN8BhBhqPlEUyjQM53WNItOjw/FQbfrPpzCTU9U+mcX4hZuhrmatU/ONiSQacxVAWCN3eyi2cWkRH2lgG93lcF7bxOyFGcQocXU18BCcE2eGnWKhbgxyQG2HEDYZRj/W8cmDh4NXilvT84c+9cRT2WArc1h5MuswODFiyOU6JN9tb5hEbn91wYvG0dCFZ8p1Es/uL30RNeU2Bijo2raNkg4ltWeVSyfr4r8zJCI4p/7izJ93NXX3zUY5uHj1WBqBEeRWicKdOJS+zbGcMkbvw2YlBHg5LNioSsKkjAKCI2fFei9cn/bz0HxtDEaiG4VCCUww6UGHzVN71SkdCkY2MD7i4dp7tYBPWWk9XE7Ptqq70=
